import { describe, expect, it } from 'vitest';
import { generateComicInfo } from '@/src/shared/comicinfo-generator';
import type { ComicInfoV2 } from '@/src/types/comic-info';

export function registerComicInfoGenerateCases(): void {
  describe('generateComicInfo', () => {
    describe('Basic XML generation', () => {
      it('generates valid XML structure', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Test Chapter',
          Series: 'Test Series',
          Number: '1',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<?xml version="1.0" encoding="utf-8"?>');
        expect(result).toContain('<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
        expect(result).toContain('</ComicInfo>');
      });

      it('includes all provided basic metadata fields', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Series: 'My Manga',
          Number: '1',
          Volume: 1,
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Title>Chapter 1</Title>');
        expect(result).toContain('<Series>My Manga</Series>');
        expect(result).toContain('<Number>1</Number>');
        expect(result).toContain('<Volume>1</Volume>');
      });

      it('adds PageCount when provided', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
        };

        const result = generateComicInfo(metadata, 25);

        expect(result).toContain('<PageCount>25</PageCount>');
      });

      it('adds generation notes automatically', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('Generated by Tako Manga Downloader (TMD)');
        expect(result).toContain('https://github.com/oovz/Tako');
      });

      it('preserves existing notes and appends generation info', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Notes: 'Original notes',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('Original notes');
        expect(result).toContain('Generated by Tako Manga Downloader (TMD)');
      });
    });

    describe('Field ordering', () => {
      it('outputs fields in correct ComicInfo v2.0 order', () => {
        const metadata: ComicInfoV2 = {
          Publisher: 'Test Publisher',
          Writer: 'Test Author',
          Series: 'Test Series',
          Title: 'Test Chapter',
          Number: '1',
        };

        const result = generateComicInfo(metadata);
        expect(result).not.toBeNull();
        if (result === null) {
          throw new Error('Expected ComicInfo XML to be generated');
        }

        const titleIndex = result.indexOf('<Title>');
        const seriesIndex = result.indexOf('<Series>');
        const numberIndex = result.indexOf('<Number>');
        const writerIndex = result.indexOf('<Writer>');
        const publisherIndex = result.indexOf('<Publisher>');

        expect(titleIndex).toBeLessThan(seriesIndex);
        expect(seriesIndex).toBeLessThan(numberIndex);
        expect(numberIndex).toBeLessThan(writerIndex);
        expect(writerIndex).toBeLessThan(publisherIndex);
      });
    });

    describe('XML escaping', () => {
      it('escapes < and > characters', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Test <Chapter> Name',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('&lt;Chapter&gt;');
        expect(result).not.toContain('<Chapter>');
      });

      it('escapes & character', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Rock & Roll',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('Rock &amp; Roll');
      });

      it('escapes quotes', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter "The End"',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('&quot;The End&quot;');
      });

      it('escapes apostrophes', () => {
        const metadata: ComicInfoV2 = {
          Title: "Hero's Journey",
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('Hero&apos;s Journey');
      });

      it('handles multiple special characters in one string', () => {
        const metadata: ComicInfoV2 = {
          Summary: '<Chapter 5> "The Final Battle" - Heroes & Villains',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('&lt;Chapter 5&gt; &quot;The Final Battle&quot; - Heroes &amp; Villains');
      });
    });

    describe('Creator fields', () => {
      it('includes all creator fields', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Writer: 'John Doe',
          Penciller: 'Jane Smith',
          Inker: 'Bob Johnson',
          Colorist: 'Alice Brown',
          Letterer: 'Charlie Wilson',
          CoverArtist: 'Dave Lee',
          Editor: 'Eve Davis',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Writer>John Doe</Writer>');
        expect(result).toContain('<Penciller>Jane Smith</Penciller>');
        expect(result).toContain('<Inker>Bob Johnson</Inker>');
        expect(result).toContain('<Colorist>Alice Brown</Colorist>');
        expect(result).toContain('<Letterer>Charlie Wilson</Letterer>');
        expect(result).toContain('<CoverArtist>Dave Lee</CoverArtist>');
        expect(result).toContain('<Editor>Eve Davis</Editor>');
      });

      it('handles comma-separated multiple creators', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Writer: 'John Doe, Jane Smith',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Writer>John Doe, Jane Smith</Writer>');
      });
    });

    describe('Publication date fields', () => {
      it('includes year, month, and day', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Year: 2024,
          Month: 6,
          Day: 15,
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Year>2024</Year>');
        expect(result).toContain('<Month>6</Month>');
        expect(result).toContain('<Day>15</Day>');
      });

      it('handles partial dates (year only)', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Year: 2024,
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Year>2024</Year>');
        expect(result).not.toContain('<Month>');
        expect(result).not.toContain('<Day>');
      });
    });

    describe('Alternative series fields', () => {
      it('includes alternative series information', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          AlternateSeries: 'Alternative Title',
          AlternateNumber: '5',
          AlternateCount: 100,
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<AlternateSeries>Alternative Title</AlternateSeries>');
        expect(result).toContain('<AlternateNumber>5</AlternateNumber>');
        expect(result).toContain('<AlternateCount>100</AlternateCount>');
      });
    });

    describe('Manga and content flags', () => {
      it('sets Manga flag to Yes', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Manga: 'Yes',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Manga>Yes</Manga>');
      });

      it('handles BlackAndWhite flag', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          BlackAndWhite: 'No',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<BlackAndWhite>No</BlackAndWhite>');
      });

      it('defaults unsupported Manga enum values to Yes', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Manga: 'InvalidValue' as unknown as 'Yes',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Manga>Yes</Manga>');
      });
    });

    describe('Additional metadata fields', () => {
      it('includes genre and characters', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Genre: 'Action, Adventure, Fantasy',
          Characters: 'Hero, Villain, Sidekick',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Genre>Action, Adventure, Fantasy</Genre>');
        expect(result).toContain('<Characters>Hero, Villain, Sidekick</Characters>');
      });

      it('includes web URL', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Web: 'https://example.com/chapter/1',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Web>https://example.com/chapter/1</Web>');
      });

      it('includes language ISO code', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          LanguageISO: 'en',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<LanguageISO>en</LanguageISO>');
      });

      it('includes summary and notes', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Summary: 'An epic battle begins',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Summary>An epic battle begins</Summary>');
        expect(result).toContain('<Notes>');
      });
    });

    describe('Volume handling', () => {
      it('includes volume number when provided', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Series: 'Test Series',
          Volume: 3,
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Volume>3</Volume>');
      });

      it('omits volume when not provided', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Series: 'Test Series',
        };

        const result = generateComicInfo(metadata);

        expect(result).not.toContain('<Volume>');
      });
    });

    describe('Data cleaning and validation', () => {
      it('removes empty strings', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Series: '',
          Writer: '   ',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Title>Chapter 1</Title>');
        expect(result).toContain('<Series>Unknown Series</Series>');
        expect(result).toContain('<LanguageISO>und</LanguageISO>');
        expect(result).not.toContain('<Writer>');
      });

      it('removes null and undefined values', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Series: null as unknown as string,
          Writer: undefined,
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Title>Chapter 1</Title>');
        expect(result).toContain('<Series>Unknown Series</Series>');
        expect(result).toContain('<LanguageISO>und</LanguageISO>');
        expect(result).not.toContain('<Writer>');
      });

      it('trims whitespace from string values', () => {
        const metadata: ComicInfoV2 = {
          Title: '  Chapter 1  ',
          Series: '\tTest Series\n',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Title>Chapter 1</Title>');
        expect(result).toContain('<Series>Test Series</Series>');
      });

      it('converts string numbers to numbers for numeric fields', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Year: '2024' as unknown as number,
          Month: '6' as unknown as number,
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Year>2024</Year>');
        expect(result).toContain('<Month>6</Month>');
      });
    });

    describe('Edge cases and error handling', () => {
      it('handles empty metadata object', () => {
        const result = generateComicInfo({});

        expect(result).toContain('<?xml version="1.0"');
        expect(result).toContain('<ComicInfo');
        expect(result).toContain('</ComicInfo>');
        expect(result).toContain('Generated by Tako Manga Downloader');
      });

      it('handles missing metadata (undefined)', () => {
        const result = generateComicInfo(undefined);

        expect(result).toContain('<ComicInfo');
        expect(result).toContain('</ComicInfo>');
      });

      it('handles very long text fields', () => {
        const longText = 'A'.repeat(5000);
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Summary: longText,
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain(`<Summary>${longText}</Summary>`);
      });

      it('handles unicode characters in metadata', () => {
        const metadata: ComicInfoV2 = {
          Title: '第1章',
          Series: 'マンガ',
          Writer: '作者名',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Title>第1章</Title>');
        expect(result).toContain('<Series>マンガ</Series>');
        expect(result).toContain('<Writer>作者名</Writer>');
      });

      it('handles emoji in metadata', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1 🔥',
          Summary: 'Epic battle 💥',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Title>Chapter 1 🔥</Title>');
        expect(result).toContain('<Summary>Epic battle 💥</Summary>');
      });

      it('enforces minimum metadata contract: Series is always present', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Series>Unknown Series</Series>');
      });

      it('enforces minimum metadata contract: LanguageISO is always present', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Series: 'Test Series',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<LanguageISO>und</LanguageISO>');
      });

      it('enforces minimum metadata contract: Manga direction for japanese language', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
          Series: 'Test Series',
          LanguageISO: 'ja',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('<Manga>Yes</Manga>');
      });
    });

    describe('Version support', () => {
      it('defaults to version 2.0', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
        };

        const result = generateComicInfo(metadata);

        expect(result).toContain('xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
      });

      it('explicitly uses version 2.0', () => {
        const metadata: ComicInfoV2 = {
          Title: 'Chapter 1',
        };

        const result = generateComicInfo(metadata, 0, '2.0');

        expect(result).toContain('xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
      });

      it('filters fields not supported in v2.0', () => {
        const metadataWithExtra = {
          Title: 'Chapter 1',
          UnsupportedField: 'test',
        } as ComicInfoV2;

        const result = generateComicInfo(metadataWithExtra);

        expect(result).toContain('<Title>Chapter 1</Title>');
      });
    });
  });
}
