import { describe, it, expect, vi } from 'vitest';
import {
  generateComicInfo,
  validateComicInfo,
  getSupportedFields,
  connectorSupportsMetadata,
  COMICINFO_FIELDS,
  COMICINFO_VERSION_SUPPORT,
} from '@/src/lib/comicinfo-generator';
import type { ComicInfoUnified } from '@/src/types/index';

describe('generateComicInfo', () => {
  describe('Basic XML generation', () => {
    it('generates valid XML structure', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Test Chapter',
        Series: 'Test Series',
        Number: '1',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<?xml version="1.0" encoding="utf-8"?>');
      expect(result).toContain('<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
      expect(result).toContain('</ComicInfo>');
    });

    it('includes all provided basic metadata fields', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Series: 'My Manga',
        Number: '1',
        Volume: 1,
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Title>Chapter 1</Title>');
      expect(result).toContain('<Series>My Manga</Series>');
      expect(result).toContain('<Number>1</Number>');
      expect(result).toContain('<Volume>1</Volume>');
    });

    it('adds PageCount when provided', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
      };
      
      const result = generateComicInfo(metadata, 25);
      
      expect(result).toContain('<PageCount>25</PageCount>');
    });

    it('adds generation notes automatically', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('Generated by Tako Manga Downloader Extension');
      expect(result).toContain('https://github.com/oovz/Tako');
    });

    it('preserves existing notes and appends generation info', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Notes: 'Original notes',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('Original notes');
      expect(result).toContain('Generated by Tako Manga Downloader Extension');
    });
  });

  describe('Field ordering', () => {
    it('outputs fields in correct ComicInfo v2.0 order', () => {
      const metadata: ComicInfoUnified = {
        Publisher: 'Test Publisher',
        Writer: 'Test Author',
        Series: 'Test Series',
        Title: 'Test Chapter',
        Number: '1',
      };
      
      const result = generateComicInfo(metadata);
      
      // Extract field order from XML
      const titleIndex = result!.indexOf('<Title>');
      const seriesIndex = result!.indexOf('<Series>');
      const numberIndex = result!.indexOf('<Number>');
      const writerIndex = result!.indexOf('<Writer>');
      const publisherIndex = result!.indexOf('<Publisher>');
      
      // Verify correct order: Title, Series, Number before Writer and Publisher
      expect(titleIndex).toBeLessThan(seriesIndex);
      expect(seriesIndex).toBeLessThan(numberIndex);
      expect(numberIndex).toBeLessThan(writerIndex);
      expect(writerIndex).toBeLessThan(publisherIndex);
    });
  });

  describe('XML escaping', () => {
    it('escapes < and > characters', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Test <Chapter> Name',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('&lt;Chapter&gt;');
      expect(result).not.toContain('<Chapter>');
    });

    it('escapes & character', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Rock & Roll',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('Rock &amp; Roll');
    });

    it('escapes quotes', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter "The End"',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('&quot;The End&quot;');
    });

    it('escapes apostrophes', () => {
      const metadata: ComicInfoUnified = {
        Title: "Hero's Journey",
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('Hero&apos;s Journey');
    });

    it('handles multiple special characters in one string', () => {
      const metadata: ComicInfoUnified = {
        Summary: '<Chapter 5> "The Final Battle" - Heroes & Villains',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('&lt;Chapter 5&gt; &quot;The Final Battle&quot; - Heroes &amp; Villains');
    });
  });

  describe('Creator fields', () => {
    it('includes all creator fields', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Writer: 'John Doe',
        Penciller: 'Jane Smith',
        Inker: 'Bob Johnson',
        Colorist: 'Alice Brown',
        Letterer: 'Charlie Wilson',
        CoverArtist: 'Dave Lee',
        Editor: 'Eve Davis',
        Translator: 'Frank Chen',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Writer>John Doe</Writer>');
      expect(result).toContain('<Penciller>Jane Smith</Penciller>');
      expect(result).toContain('<Inker>Bob Johnson</Inker>');
      expect(result).toContain('<Colorist>Alice Brown</Colorist>');
      expect(result).toContain('<Letterer>Charlie Wilson</Letterer>');
      expect(result).toContain('<CoverArtist>Dave Lee</CoverArtist>');
      expect(result).toContain('<Editor>Eve Davis</Editor>');
      expect(result).toContain('<Translator>Frank Chen</Translator>');
    });

    it('handles comma-separated multiple creators', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Writer: 'John Doe, Jane Smith',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Writer>John Doe, Jane Smith</Writer>');
    });
  });

  describe('Publication date fields', () => {
    it('includes year, month, and day', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Year: 2024,
        Month: 6,
        Day: 15,
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Year>2024</Year>');
      expect(result).toContain('<Month>6</Month>');
      expect(result).toContain('<Day>15</Day>');
    });

    it('handles partial dates (year only)', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Year: 2024,
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Year>2024</Year>');
      expect(result).not.toContain('<Month>');
      expect(result).not.toContain('<Day>');
    });
  });

  describe('Alternative series fields', () => {
    it('includes alternative series information', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        AlternateSeries: 'Alternative Title',
        AlternateNumber: '5',
        AlternateCount: 100,
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<AlternateSeries>Alternative Title</AlternateSeries>');
      expect(result).toContain('<AlternateNumber>5</AlternateNumber>');
      expect(result).toContain('<AlternateCount>100</AlternateCount>');
    });
  });

  describe('Manga and content flags', () => {
    it('sets Manga flag to Yes', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Manga: 'Yes',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Manga>Yes</Manga>');
    });

    it('handles BlackAndWhite flag', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        BlackAndWhite: 'No',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<BlackAndWhite>No</BlackAndWhite>');
    });

    it('defaults unsupported Manga enum values to Yes', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Manga: 'InvalidValue' as unknown,
      };
      
      const result = generateComicInfo(metadata);
      
      // Should fallback to 'Yes' for invalid enum
      expect(result).toContain('<Manga>Yes</Manga>');
    });
  });

  describe('Additional metadata fields', () => {
    it('includes genre and characters', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Genre: 'Action, Adventure, Fantasy',
        Characters: 'Hero, Villain, Sidekick',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Genre>Action, Adventure, Fantasy</Genre>');
      expect(result).toContain('<Characters>Hero, Villain, Sidekick</Characters>');
    });

    it('includes web URL', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Web: 'https://example.com/chapter/1',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Web>https://example.com/chapter/1</Web>');
    });

    it('includes language ISO code', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        LanguageISO: 'en',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<LanguageISO>en</LanguageISO>');
    });

    it('includes summary and notes', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Summary: 'An epic battle begins',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Summary>An epic battle begins</Summary>');
      expect(result).toContain('<Notes>');
    });
  });

  describe('Volume handling', () => {
    it('includes volume number when provided', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Series: 'Test Series',
        Volume: 3,
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Volume>3</Volume>');
    });

    it('omits volume when not provided', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Series: 'Test Series',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).not.toContain('<Volume>');
    });
  });

  describe('Data cleaning and validation', () => {
    it('removes empty strings', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Series: '',
        Writer: '   ',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Title>Chapter 1</Title>');
      expect(result).not.toContain('<Series>');
      expect(result).not.toContain('<Writer>');
    });

    it('removes null and undefined values', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Series: null as unknown,
        Writer: undefined,
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Title>Chapter 1</Title>');
      expect(result).not.toContain('<Series>');
      expect(result).not.toContain('<Writer>');
    });

    it('trims whitespace from string values', () => {
      const metadata: ComicInfoUnified = {
        Title: '  Chapter 1  ',
        Series: '\tTest Series\n',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Title>Chapter 1</Title>');
      expect(result).toContain('<Series>Test Series</Series>');
    });

    it('converts string numbers to numbers for numeric fields', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Year: '2024' as unknown,
        Month: '6' as unknown,
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Year>2024</Year>');
      expect(result).toContain('<Month>6</Month>');
    });
  });

  describe('Edge cases and error handling', () => {
    it('handles empty metadata object', () => {
      const result = generateComicInfo({});
      
      expect(result).toContain('<?xml version="1.0"');
      expect(result).toContain('<ComicInfo');
      expect(result).toContain('</ComicInfo>');
      expect(result).toContain('Generated by Tako');
    });

    it('handles missing metadata (undefined)', () => {
      const result = generateComicInfo(undefined);
      
      expect(result).toContain('<ComicInfo');
      expect(result).toContain('</ComicInfo>');
    });

    it('handles very long text fields', () => {
      const longText = 'A'.repeat(5000);
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
        Summary: longText,
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain(`<Summary>${longText}</Summary>`);
    });

    it('handles unicode characters in metadata', () => {
      const metadata: ComicInfoUnified = {
        Title: '第1章',
        Series: 'マンガ',
        Writer: '作者名',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Title>第1章</Title>');
      expect(result).toContain('<Series>マンガ</Series>');
      expect(result).toContain('<Writer>作者名</Writer>');
    });

    it('handles emoji in metadata', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1 🔥',
        Summary: 'Epic battle 💥',
      };
      
      const result = generateComicInfo(metadata);
      
      expect(result).toContain('<Title>Chapter 1 🔥</Title>');
      expect(result).toContain('<Summary>Epic battle 💥</Summary>');
    });
  });

  describe('Version support', () => {
    it('defaults to version 2.0', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
      };
      
      const result = generateComicInfo(metadata);
      
      // v2.0 should have proper namespace
      expect(result).toContain('xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
    });

    it('explicitly uses version 2.0', () => {
      const metadata: ComicInfoUnified = {
        Title: 'Chapter 1',
      };
      
      const result = generateComicInfo(metadata, 0, '2.0');
      
      expect(result).toContain('xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"');
    });

    it('filters fields not supported in v2.0', () => {
      const metadataWithExtra: unknown = {
        Title: 'Chapter 1',
        // Add unsupported field (doesn't exist in v2.0 spec)
        UnsupportedField: 'test',
      };
      
      const result = generateComicInfo(metadataWithExtra);
      
      expect(result).toContain('<Title>Chapter 1</Title>');
      // UnsupportedField should be filtered out or ignored
    });
  });
});

describe('validateComicInfo', () => {
  it('validates correct metadata', () => {
    const metadata: ComicInfoUnified = {
      Title: 'Chapter 1',
      Series: 'Test Series',
      Number: '1',
    };
    
    const result = validateComicInfo(metadata);
    
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it('reports unknown fields as warnings', () => {
    const metadataWithUnknown: unknown = {
      Title: 'Chapter 1',
      UnknownField: 'value',
    };
    
    const result = validateComicInfo(metadataWithUnknown);
    
    expect(result.warnings).toContain('Unknown field: UnknownField');
  });

  it('validates numeric fields', () => {
    const metadata: ComicInfoUnified = {
      Title: 'Chapter 1',
      Year: 2024,
      Month: 6,
    };
    
    const result = validateComicInfo(metadata);
    
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  it('accepts empty metadata', () => {
    const result = validateComicInfo({});
    
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });
});

describe('getSupportedFields', () => {
  it('returns array of field definitions', () => {
    const fields = getSupportedFields();
    
    expect(Array.isArray(fields)).toBe(true);
    expect(fields.length).toBeGreaterThan(0);
  });

  it('includes field names and types', () => {
    const fields = getSupportedFields();
    const titleField = fields.find(f => f.name === 'Title');
    
    expect(titleField).toBeDefined();
    expect(titleField?.type).toBe('string');
    expect(titleField?.required).toBe(false);
  });

  it('includes all standard ComicInfo fields', () => {
    const fields = getSupportedFields();
    const fieldNames = fields.map(f => f.name);
    
    expect(fieldNames).toContain('Title');
    expect(fieldNames).toContain('Series');
    expect(fieldNames).toContain('Number');
    expect(fieldNames).toContain('Writer');
    expect(fieldNames).toContain('Year');
    expect(fieldNames).toContain('PageCount');
  });
});

describe('connectorSupportsMetadata', () => {
  it('returns true for connector with extractSeriesMetadata', () => {
    const connector = {
      series: {
        extractSeriesMetadata: vi.fn(),
      },
    };
    
    const result = connectorSupportsMetadata(connector);
    
    expect(result).toBe(true);
  });

  it('returns false for connector without series', () => {
    const connector = {};
    
    const result = connectorSupportsMetadata(connector);
    
    expect(result).toBe(false);
  });

  it('returns false for connector without extractSeriesMetadata', () => {
    const connector = {
      series: {},
    };
    
    const result = connectorSupportsMetadata(connector);
    
    expect(result).toBe(false);
  });

  it('returns false for null connector', () => {
    const result = connectorSupportsMetadata(null);
    
    expect(result).toBe(false);
  });
});

describe('COMICINFO_VERSION_SUPPORT', () => {
  it('defines version 2.0 support', () => {
    expect(COMICINFO_VERSION_SUPPORT['2.0']).toBeDefined();
    expect(COMICINFO_VERSION_SUPPORT['2.0'].version).toBe('2.0');
  });

  it('includes all v2.0 supported fields', () => {
    const fields = COMICINFO_VERSION_SUPPORT['2.0'].supportedFields;
    
    expect(fields).toContain('Title');
    expect(fields).toContain('Series');
    expect(fields).toContain('Writer');
    expect(fields).toContain('PageCount');
    expect(fields).toContain('Manga');
  });

  it('defines enum values for Manga and BlackAndWhite', () => {
    const enums = COMICINFO_VERSION_SUPPORT['2.0'].enumValues;
    
    expect(enums.Manga).toContain('Yes');
    expect(enums.Manga).toContain('No');
    expect(enums.BlackAndWhite).toContain('Yes');
    expect(enums.BlackAndWhite).toContain('No');
  });
});

describe('COMICINFO_FIELDS', () => {
  it('defines Title field', () => {
    expect(COMICINFO_FIELDS.Title).toBeDefined();
    expect(COMICINFO_FIELDS.Title.type).toBe('string');
  });

  it('defines numeric fields correctly', () => {
    expect(COMICINFO_FIELDS.Year.type).toBe('number');
    expect(COMICINFO_FIELDS.PageCount.type).toBe('number');
    expect(COMICINFO_FIELDS.Volume.type).toBe('number');
  });

  it('marks all fields as not required', () => {
    const fields = Object.values(COMICINFO_FIELDS);
    
    fields.forEach(field => {
      expect(field.required).toBe(false);
    });
  });
});
